services:
  app:
    image: burntheland/trocalivro
    container_name: trocalivro-container
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - trocalivro-network
    environment:
      - DB_HOST=trocalivro-db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=trocalivro_db
    depends_on:
      - trocalivro-db
    volumes:
      - ./:/app
    command: npm run start:dev

  trocalivro-db:
    image: postgres:16
    container_name: trocalivro-db
    environment:
      POSTGRES_DB: trocalivro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - trocalivro-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  trocalivro-network:

volumes:
  postgres-data:
